INSERT OR IGNORE INTO neighbourhoods (
  id, name, generated_by_model, source_listing_count, rent_benchmark_json, mrt_json,
  food_score, food_hawker_centres, food_supermarkets, food_convenience_stores_24h,
  food_restaurants_cafes_count, gym_score, activesg_gym, private_gyms_within_1km,
  nearest_gym_walk_minutes, parks_score, nearest_park, nearest_park_walk_minutes,
  has_large_park, healthcare_score, nearest_clinic_walk_minutes, nearest_hospital,
  nearest_hospital_minutes, quietness_score, noise_profile, area_type,
  lifestyle_tags_json, source_evidence_json
) VALUES
  ('one_north', 'One-North', 'manual-observation-from-listing-sample', 7, '{"common_room":{"min":1600,"max":2900,"typical":1900},"master_room":{"min":2500,"max":2700,"typical":2600}}', '{"nearest_station":"One-North MRT","walk_minutes":5,"lines":["Circle Line"],"stations_within_10min":2}', 8, 1, 2, 2, 'many', 7, 0, 3, 8, 6, 'one-north Park', 8, 0, 8, 8, 'National University Hospital', 12, 6, 'Business park and condo cluster; convenient but less quiet during office hours.', 'mixed', '["mrt-accessible","expat-popular","premium","student-friendly"]', '["10-listing manual sample near Shopee 138522","Google indexed snippets"]'),
  ('buona_vista', 'Buona Vista', 'manual-observation-from-listing-sample', 2, '{"common_room":{"min":1350,"max":1680,"typical":1600},"master_room":{"min":1450,"max":2600,"typical":2000}}', '{"nearest_station":"Buona Vista MRT","walk_minutes":8,"lines":["East-West Line","Circle Line"],"stations_within_10min":2}', 8, 2, 2, 2, 'many', 7, 0, 2, 10, 7, 'one-north Park', 10, 0, 8, 8, 'National University Hospital', 10, 7, 'Transit-friendly residential and research-office fringe near Rochester and Holland.', 'mixed', '["mrt-accessible","hawker-nearby","student-friendly","premium"]', '["10-listing manual sample near Shopee 138522","Google indexed snippets"]'),
  ('dover', 'Dover', 'manual-observation-from-listing-sample', 1, '{"common_room":{"min":1200,"max":1600,"typical":1400},"master_room":{"min":1450,"max":1900,"typical":1650}}', '{"nearest_station":"Buona Vista MRT","walk_minutes":12,"lines":["East-West Line","Circle Line"],"stations_within_10min":1}', 7, 1, 1, 1, 'some', 6, 0, 1, 12, 7, 'one-north Park', 12, 0, 8, 8, 'National University Hospital', 10, 7, 'Residential condo/HDB fringe between Dover and Buona Vista; quieter than the one-north core.', 'residential', '["student-friendly","quiet","mrt-accessible"]', '["10-listing manual sample near Shopee 138522","Google indexed snippets"]');

INSERT OR IGNORE INTO neighbourhood_aliases (alias, neighbourhood_id, match_method, confidence) VALUES
  ('One-North', 'one_north', 'manual', 0.95),
  ('One-North Residences', 'one_north', 'manual', 0.95),
  ('One-North Eden', 'one_north', 'manual', 0.95),
  ('North Buona Vista Road', 'one_north', 'manual', 0.85),
  ('Buona Vista Gardens', 'buona_vista', 'manual', 0.85),
  ('The Rochester Residences', 'buona_vista', 'manual', 0.9),
  ('Dover Parkview', 'dover', 'manual', 0.9);

INSERT OR IGNORE INTO postal_to_neighbourhood (postal_prefix, neighbourhood_id, confidence) VALUES
  ('138', 'one_north', 0.75),
  ('118', 'buona_vista', 0.6);

INSERT OR IGNORE INTO listing_import_batches (id, source, source_uri, record_count, status, notes) VALUES
  (
    2,
    'manual-public-web-sample-shopee-138522',
    'Google indexed snippets from 99.co and PropertyGuru searches around One-North / Buona Vista / Dover',
    10,
    'completed',
    'Manual sample of publicly visible room rental listing snippets near Shopee Singapore, 5 Science Park Drive, postal 138522. Fields not visible in snippets are inferred only when low-risk and documented in raw_payload_json.'
  );

INSERT OR IGNORE INTO listings (
  id, import_batch_id, source, source_listing_id, neighbourhood_id, address, postal_code,
  latitude, longitude, room_type, rent, currency, lease_term_months, available_from,
  aircon, wifi, cooking, private_bath, furnished, washing_machine, property_type,
  floor_level, facing, image_url, listing_url, posted_date, agent_name,
  is_direct_landlord, raw_payload_json
) VALUES
  (
    '99co-one-north-residences-AdxkXTafCaEuttWSWYFupH',
    2,
    '99.co',
    'one-north-residences-condo-AdxkXTafCaEuttWSWYFupH',
    'one_north',
    'One-North Residences, 7 One-North Gateway',
    '138642',
    1.2996,
    103.7879,
    'master_room',
    2599,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    1,
    1,
    1,
    'Apartment',
    'unknown',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/one-north-residences-condo-AdxkXTafCaEuttWSWYFupH',
    NULL,
    NULL,
    NULL,
    '{"title":"Master Room (Condo) for Rent in *One-North Residences","source_snippet":"View all details on this S$ 2599, 220 sqft Apartment Room for Rent including photos, map, prices, floor plan, nearby supermarkets and MRT stations.","area_context":"One-North / Buona Vista, close to Shopee Singapore 138522","listing_size_sqft":220,"characteristics":["premium master room","largest room in sample","likely walkable or short bus to Shopee Science Park"],"filled_observations":{"neighbourhood_id":"one_north","coordinates":"approximate for One-North Residences / One-North Gateway","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","aircon_wifi_furnished_washer":"inferred typical for condo room rental; verify before use","private_bath":"inferred from master room"},"analysis":{"rent_tier":"high","space_tier":"large","commute_fit_for_shopee_138522":"strong","data_confidence":"medium","extraction_method":"google_indexed_snippet"}}'
  ),
  (
    '99co-one-north-residences-RUtgg55YryRwtMtnLbLi6t',
    2,
    '99.co',
    'one-north-residences-condo-RUtgg55YryRwtMtnLbLi6t',
    'one_north',
    'One-North Residences, 7 One-North Gateway',
    '138642',
    1.2996,
    103.7879,
    'master_room',
    2600,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    1,
    1,
    1,
    'Condo',
    'low',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/one-north-residences-condo-RUtgg55YryRwtMtnLbLi6t',
    NULL,
    NULL,
    NULL,
    '{"title":"Master Room (Condo) for Rent in *One-North Residences","source_snippet":"One-North Residences Ensuite Room for rental now all lady unit. Unit at blk 7 #04 available for rent now. Up to 2 pax rental at $2700; one pax $2600 nett.","area_context":"One-North / Buona Vista, close to Shopee Singapore 138522","characteristics":["ensuite/private bathroom indicated","all-lady unit","supports one or two occupants","available now","low floor inferred from #04"],"filled_observations":{"neighbourhood_id":"one_north","coordinates":"approximate for One-North Residences / One-North Gateway","lease_term_months":"assumed standard 12-month room lease","available_from":"explicitly available now in snippet","private_bath":"ensuite room stated in snippet","aircon_wifi_furnished_washer":"inferred typical for condo room rental; verify before use"},"analysis":{"rent_tier":"high","space_tier":"unknown","commute_fit_for_shopee_138522":"strong","data_confidence":"medium","extraction_method":"google_indexed_snippet"}}'
  ),
  (
    '99co-north-buona-vista-road-DJBMdwnjPZuKhSBBkJnh5V',
    2,
    '99.co',
    'north-buona-vista-road-condo-DJBMdwnjPZuKhSBBkJnh5V',
    'one_north',
    'North Buona Vista Road',
    '138xxx',
    1.3060,
    103.7900,
    'master_room',
    2600,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    1,
    1,
    1,
    'Condo',
    'unknown',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/north-buona-vista-road-condo-DJBMdwnjPZuKhSBBkJnh5V',
    NULL,
    NULL,
    NULL,
    '{"title":"Master Room (Condo) for Rent in *North Buona Vista Road","source_snippet":"View all details on this S$ 2600, 180 sqft Condo Room for Rent including photos, map, prices, floor plan, nearby supermarkets and MRT stations.","area_context":"North Buona Vista Road near One-North and Buona Vista MRT","listing_size_sqft":180,"characteristics":["master room","condo room","central to Buona Vista / one-north employment cluster"],"filled_observations":{"neighbourhood_id":"one_north","postal_code":"partial district-level observation only","coordinates":"approximate point along North Buona Vista Road","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"inferred from master room","aircon_wifi_furnished_washer":"inferred typical for condo room rental; verify before use"},"analysis":{"rent_tier":"high","space_tier":"medium-large","commute_fit_for_shopee_138522":"strong","data_confidence":"medium","extraction_method":"google_indexed_snippet"}}'
  ),
  (
    '99co-one-north-residences-frVB7vEYvgPjuryZSuZa3g',
    2,
    '99.co',
    'one-north-residences-condo-frVB7vEYvgPjuryZSuZa3g',
    'one_north',
    'One-North Residences, 7 One-North Gateway',
    '138642',
    1.2996,
    103.7879,
    'common_room',
    1680,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    0,
    1,
    1,
    'Condo',
    'unknown',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/one-north-residences-condo-frVB7vEYvgPjuryZSuZa3g',
    NULL,
    NULL,
    NULL,
    '{"title":"Condo for Room Rent: One-North Residences - Singapore","source_snippet":"View all details on this S$ 1680, 120 sqft Condo Room for Rent including photos, map, prices, floor plan, nearby supermarkets and MRT stations.","area_context":"One-North Residences, close to One-North MRT and Shopee 138522","listing_size_sqft":120,"characteristics":["condo room","lower rent than master-room options","compact size"],"filled_observations":{"neighbourhood_id":"one_north","coordinates":"approximate for One-North Residences / One-North Gateway","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"set false because row is treated as common room","aircon_wifi_furnished_washer":"inferred typical for condo room rental; verify before use"},"analysis":{"rent_tier":"mid","space_tier":"compact","commute_fit_for_shopee_138522":"strong","data_confidence":"medium","extraction_method":"google_indexed_snippet","room_type_confidence":"low; snippet says room but not common/master"}}'
  ),
  (
    '99co-one-north-residences-NRJNDbL4xt8j8Nck753J9e',
    2,
    '99.co',
    'one-north-residences-condo-NRJNDbL4xt8j8Nck753J9e',
    'one_north',
    'One-North Residences, 7 One-North Gateway',
    '138642',
    1.2996,
    103.7879,
    'master_room',
    2500,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    1,
    1,
    1,
    'Apartment',
    'unknown',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/one-north-residences-condo-NRJNDbL4xt8j8Nck753J9e',
    NULL,
    NULL,
    NULL,
    '{"title":"Master Room (Condo) for Rent in *One-North Residences","source_snippet":"View all details on this S$ 2500, 200 sqft Apartment Room for Rent including photos, map, prices, floor plan, nearby supermarkets and MRT stations.","area_context":"One-North Residences, close to One-North MRT and Shopee 138522","listing_size_sqft":200,"characteristics":["master room","large room","slightly cheaper than similar 99.co master listings in the same property"],"filled_observations":{"neighbourhood_id":"one_north","coordinates":"approximate for One-North Residences / One-North Gateway","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"inferred from master room","aircon_wifi_furnished_washer":"inferred typical for condo room rental; verify before use"},"analysis":{"rent_tier":"high","space_tier":"large","commute_fit_for_shopee_138522":"strong","data_confidence":"medium","extraction_method":"google_indexed_snippet"}}'
  ),
  (
    '99co-one-north-eden-aQWMXZZmByTZk4iz4QPBnE',
    2,
    '99.co',
    'one-north-eden-condo-aQWMXZZmByTZk4iz4QPBnE',
    'one_north',
    'One-North Eden',
    '138xxx',
    1.3003,
    103.7897,
    'common_room',
    2900,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    0,
    1,
    1,
    'Condo',
    'unknown',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/one-north-eden-condo-aQWMXZZmByTZk4iz4QPBnE',
    '2026-05-31',
    NULL,
    NULL,
    '{"title":"Condo for Room Rent: One-North Eden. - Singapore - 99.co","source_snippet":"6 days ago — View all details on this S$ 2900, 120 sqft Condo Room for Rent including photos, map, prices, floor plan, nearby supermarkets and MRT ...","area_context":"One-North Eden near One-North / Buona Vista MRT","listing_size_sqft":120,"characteristics":["newer condo project","very high rent for compact size","likely premium building/location pricing","recently posted around 2026-05-31 based on 6-days-ago snippet"],"filled_observations":{"neighbourhood_id":"one_north","postal_code":"partial district-level observation only","coordinates":"approximate for One-North Eden area","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"set false because row is treated as common room","aircon_wifi_furnished_washer":"inferred typical for new condo room rental; verify before use"},"analysis":{"rent_tier":"very_high","space_tier":"compact","commute_fit_for_shopee_138522":"strong","data_confidence":"medium","extraction_method":"google_indexed_snippet","room_type_confidence":"low; snippet says room but not common/master"}}'
  ),
  (
    '99co-one-north-residences-cG2m9W3vFiw3bTg5REwSTC',
    2,
    '99.co',
    'one-north-residences-condo-cG2m9W3vFiw3bTg5REwSTC',
    'one_north',
    'One-North Residences, 7 One-North Gateway',
    '138642',
    1.2996,
    103.7879,
    'common_room',
    1680,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    0,
    1,
    1,
    'Apartment',
    'unknown',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/one-north-residences-condo-cG2m9W3vFiw3bTg5REwSTC',
    NULL,
    NULL,
    NULL,
    '{"title":"Common Room (Condo) for Rent in *One-North Residences","source_snippet":"View all details on this S$ 1680, 180 sqft Apartment Room for Rent including photos, map, prices, floor plan, nearby supermarkets and MRT stations.","area_context":"One-North Residences, close to One-North MRT and Shopee 138522","listing_size_sqft":180,"characteristics":["common room","larger than many common-room samples","same rent as smaller One-North Residences room snippet"],"filled_observations":{"neighbourhood_id":"one_north","coordinates":"approximate for One-North Residences / One-North Gateway","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"set false because row is common room","aircon_wifi_furnished_washer":"inferred typical for condo room rental; verify before use"},"analysis":{"rent_tier":"mid","space_tier":"medium-large","commute_fit_for_shopee_138522":"strong","data_confidence":"medium","extraction_method":"google_indexed_snippet"}}'
  ),
  (
    '99co-buona-vista-gardens-5hP4VaAv7oBQMVryiRkCDy',
    2,
    '99.co',
    'buona-vista-gardens-condo-5hP4VaAv7oBQMVryiRkCDy',
    'buona_vista',
    'Buona Vista Gardens',
    '118xxx',
    1.3090,
    103.7870,
    'common_room',
    1350,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    0,
    1,
    1,
    'Condo',
    'unknown',
    'unknown',
    NULL,
    'https://www.99.co/singapore/rooms/property/buona-vista-gardens-condo-5hP4VaAv7oBQMVryiRkCDy',
    NULL,
    NULL,
    NULL,
    '{"title":"Condo for Room Rent: Buona Vista Gardens - Singapore","source_snippet":"View all details on this S$ 1350, 100 sqft Condo Room for Rent including photos, map, prices, floor plan, nearby supermarkets and MRT stations.","area_context":"Buona Vista area, likely short commute to Shopee 138522","listing_size_sqft":100,"characteristics":["lowest 99.co rent in sample","compact room","likely better value if exact commute is acceptable"],"filled_observations":{"neighbourhood_id":"buona_vista","postal_code":"partial district-level observation only","coordinates":"approximate for Buona Vista Gardens area","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"set false because row is treated as common room","aircon_wifi_furnished_washer":"inferred typical for condo room rental; verify before use"},"analysis":{"rent_tier":"lower_mid","space_tier":"small","commute_fit_for_shopee_138522":"good","data_confidence":"medium","extraction_method":"google_indexed_snippet","room_type_confidence":"low; snippet says room but not common/master"}}'
  ),
  (
    'pg-dover-parkview-one-north-snippet-1450',
    2,
    'propertyguru',
    'pg-dover-parkview-one-north-snippet-1450',
    'dover',
    'Dover Parkview, 36 Dover Rise',
    '138685',
    1.3061,
    103.7806,
    'master_room',
    1450,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    1,
    1,
    1,
    'Condominium',
    'unknown',
    'unknown',
    NULL,
    'https://www.propertyguru.com.sg/property-for-rent/near-cc23-one-north-mrt-station-1658/room-rental',
    NULL,
    NULL,
    NULL,
    '{"title":"12 Mins walk to Buona Vista MRT coliving condo room for rent","source_snippet":"S$ 1,450 /mo. Dover Parkview. 36 Dover Rise. Master Room. 5 pax. 110 sqft. Condominium. Built: 1997.","area_context":"Dover / Buona Vista, near One-North MRT search area","listing_size_sqft":110,"built_year":1997,"characteristics":["lower rent for a master room","older condominium","12 minutes walk to Buona Vista MRT according to snippet","coliving setup with 5 pax stated"],"filled_observations":{"neighbourhood_id":"dover","coordinates":"approximate for Dover Parkview / Dover Rise","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"inferred from master room","aircon_wifi_furnished_washer":"inferred typical for coliving condo room; verify before use"},"analysis":{"rent_tier":"lower_mid","space_tier":"small","commute_fit_for_shopee_138522":"good","data_confidence":"medium_low","extraction_method":"google_indexed_snippet"}}'
  ),
  (
    'pg-rochester-residences-one-north-snippet-1600',
    2,
    'propertyguru',
    'pg-rochester-residences-one-north-snippet-1600',
    'buona_vista',
    'The Rochester Residences, 33 Rochester Drive',
    '138638',
    1.3052,
    103.7887,
    'common_room',
    1600,
    'SGD',
    12,
    '2026-06-06',
    1,
    1,
    NULL,
    0,
    1,
    1,
    'Apartment',
    'unknown',
    'unknown',
    NULL,
    'https://www.propertyguru.com.sg/apartment-for-rent/near-cc23-one-north-mrt-station-1658/priced-under-4k-sgd',
    NULL,
    NULL,
    NULL,
    '{"title":"Prime Buona Vista Condo Room Available for Rent","source_snippet":"S$ 1,600 /mo. The Rochester Residences. 33 Rochester Drive. Common Room. 6 pax. 165 sqft. Apartment. Built: 2011.","area_context":"Rochester / Buona Vista, close to Buona Vista MRT and One-North","listing_size_sqft":165,"built_year":2011,"characteristics":["common room","good room size for rent","prime Buona Vista / Rochester location","6 pax household size stated"],"filled_observations":{"neighbourhood_id":"buona_vista","coordinates":"approximate for The Rochester Residences / Rochester Drive","lease_term_months":"assumed standard 12-month room lease","available_from":"treated as available now because snippet does not show a later date","private_bath":"set false because row is common room","aircon_wifi_furnished_washer":"inferred typical for condo/apartment room rental; verify before use"},"analysis":{"rent_tier":"mid","space_tier":"medium","commute_fit_for_shopee_138522":"strong","data_confidence":"medium_low","extraction_method":"google_indexed_snippet"}}'
  );